events {}

http {
    server {
        listen 5001;

        # Proxy requests to Flask
        location / {
            proxy_pass http://localhost:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Proxy requests to noVNC
        location /novnc/ {
            alias /opt/novnc/; # Correctly serve noVNC files
            index vnc.html;
        }

        location /novnc/websockify {
            proxy_pass http://localhost:8081; # Proxy WebSocket connections
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;

            # Timeout settings
            proxy_read_timeout 3600;
            proxy_send_timeout 3600;
            proxy_buffering off;
        }

    }
}


